version: '3.4'

services:
  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: Identity.API/Dockerfile

  catalogs.api:
    image: ${DOCKER_REGISTRY-}catalogsapi
    build:
      context: .
      dockerfile: Catalogs.API/Dockerfile