version: '3.4'

services:
  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: Identity.API/Dockerfile
  catalogs.api:
    image: ${DOCKER_REGISTRY-}catalogsapi
    build:
      context: .
      dockerfile: Catalogs.API/Dockerfile
  mssql.db: 
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: catalogs.db
    ports:
        - "1433:1433"
    environment:
        - ACCEPT_EULA=y
        - MSSQL_SA_PASSWORD=A&VeryComplex123Password


