version: '3.4'

services:
  catalogs.api:
    image: ${DOCKER_REGISTRY-}catalogsapi
    build:
      context: .
      dockerfile: Catalogs.API/Dockerfile

  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: Identity.API/Dockerfile

  ocelot.webhost:
    image: ${DOCKER_REGISTRY-}ocelotwebhost
    build:
      context: .
      dockerfile: Ocelot.WebHost/Dockerfile

  baskets.api:
    image: ${DOCKER_REGISTRY-}basketsapi
    build:
      context: .
      dockerfile: Baskets.API/Dockerfile
