global using AutoMapper;
global using Baskets.BusinessLogic.Exceptions;
global using Baskets.BusinessLogic.MappingProfiles;
global using Baskets.DataAccess.Entities.Constants.Messages;
global using Baskets.UnitTests.BasketFakeDb;
global using Baskets.UnitTests.Mock;
global using Bogus;
global using FluentAssertions;
global using Moq;
